version: '3.9'
services:
  backend:
    image: ${BACKEND_IMAGE}
    container_name: pharmacy
    env_file:
      - .env.prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
      RDS_ENDPOINT: ${RDS_ENDPOINT}
    restart: unless-stopped
    ports:
      - "80:8080"
